language: python
python:
  - 2.7
install:
  - pip install . --pre
  - pip install git-lint pylint
script:
  - "if [ \"$TRAVIS_PULL_REQUEST\" != \"false\" ]; then git reset --soft ${TRAVIS_COMMIT_RANGE%...*} && git status && git log | head -n 1 && git lint; fi || true"
  - nosetests
